version: '3.9'

services:
  db:
    image: dphelpssys/local_mysql:latest
    container_name: trillium_local_mysql
    volumes:
      - ./mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: trillium_local_db
      MYSQL_USER: trilladmin
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    
  wordpress:
    image: dphelpssys/local_wp:latest
    container_name: trillium_local_wp
    volumes:
      - ./html:/var/www/html
      - ./php:/usr/local/etc/php
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: trilladmin
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: trillium_local_db
    depends_on:
      - db
      - phpmyadmin

  phpmyadmin:
   depends_on:
      - db
   image: dphelpssys/local_phpmyadmin:latest
   container_name: phpmyadmin
   restart: always
   ports:
    - 8180:80
   environment:
    PMA_HOST: db
    MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}